platform :ios, '9.0'

target 'HPBWeb3SDK' do
    inhibit_all_warnings!
    use_modular_headers!
    pod 'Alamofire', '~> 4.8.2'
    pod 'Alamofire-Synchronous'
    pod 'BigInt' , '~> 3.0.0'
    pod 'CryptoSwift', '~> 0.9.0'
    pod 'Result', '~> 3.0.0'
    pod 'libsodium', '~> 1.0.12'
    pod 'secp256k1_ios', '~> 0.1.3'

end
